### ISSUE TITLE
npm run start Error

### ISSUE THREAD

**Issue by M-Mortaz** [ceyonur/viabtc-openrpc#1]
I followed the pipeline but when execute `npm run start` the following error raise.Since I'm not familiar with Nodejs please let me know how I can resolve the issue.Thanks
```
➜  gatsby git:(main) ✗ npm run start

> ViaBTCAPI@1.0.0 start /home/parsezan/work/viabtc-openrpc/docs/gatsby
> npm run develop


> ViaBTCAPI@1.0.0 develop /home/parsezan/work/viabtc-openrpc/docs/gatsby
> gatsby develop

╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Gatsby collects anonymous usage analytics                            ║
║   to help improve Gatsby for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
║   To learn more, checkout https://gatsby.dev/telemetry                 ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
success open and validate gatsby-configs - 0.086s
success load plugins - 1.840s
success onPreInit - 0.033s
success initialize cache - 0.007s
success copy gatsby files - 0.059s
success onPreBootstrap - 0.019s
success createSchemaCustomization - 0.004s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.248s
success building schema - 0.291s
info Total nodes: 52, SitePage nodes: 2 (use --verbose for breakdown)
success createPages - 0.031s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.066s
success update schema - 0.019s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.100s
success onPostBootstrap - 0.104s
info bootstrap finished - 5.937s
success onPreExtractQueries - 0.005s
success extract queries from components - 0.547s
success write out requires - 0.003s
success run static queries - 0.045s - 5/5 110.74/s
success run page queries - 0.011s - 3/3 269.38/s
⠇ Building development bundle
TypeError: (0 , _createSvgIcon.default) is not a function
    at Object../node_modules/@xops.net/gatsby-openrpc-theme/node_modules/@material-ui/icons/Brightness3.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:42052:43)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Module../node_modules/@xops.net/gatsby-openrpc-theme/src/layouts/index.tsx (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:42290:88)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Object../node_modules/gatsby-plugin-layout/wrap-page.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:83482:26)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Object../node_modules/gatsby-plugin-layout/gatsby-ssr.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:83459:27)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Object../.cache/api-runner-ssr.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:163:11)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Module../.cache/develop-static-entry.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:559:73)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at /home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:127:18
    at /home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:130:10
    at webpackUniversalModuleDefinition (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:3:20)
    at Object.<anonymous> (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public
 ERROR 

There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help
https://gatsby.dev/debug-html TypeError: (0 , _createSvgIcon.default) is not a
function


  14 | var _createSvgIcon =
_interopRequireDefault(require("./utils/createSvgIcon"));
  15 |
> 16 | var _default = (0, _createSvgIcon.default)(
/*#__PURE__*/React.createElement("path", {
     |                ^
  17 |   d: "M9 2c-1.05 0-2.05.16-3 .46 4.06 1.27 7 5.06 7 9.54 0 4.48-2.94 
8.27-7 9.54.95.3 1.95.46 3 .46 5.52 0 10-4.48 10-10S14.52 2 9 2z"
  18 | }), 'Brightness3');
  19 |


  WebpackError: TypeError: (0 , _createSvgIcon.default) is not a function
  
  - Brightness3.js:16 
    [gatsby-openrpc-theme]/[@material-ui]/icons/Brightness3.js:16:16
  
  - wrap-page.js:12 
    node_modules/gatsby-plugin-layout/wrap-page.js:12:26
  
  - gatsby-ssr.js:3 
    node_modules/gatsby-plugin-layout/gatsby-ssr.js:3:27
  

not finished Building development bundle - 10.153s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViaBTCAPI@1.0.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ViaBTCAPI@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Ubuntu 20.04
nodejs  v10.19.0
npm  v6.14.7
nvm 0.25.0

**Comment by ceyonur** [comment]
seems like related to open-rpc/generator:
https://github.com/open-rpc/generator/issues/621

I tried to downgrade open-rpc generator to 1.18.0 but still not working. For a work aroud you can use https://playground.open-rpc.org/ and paste content of  https://github.com/ceyonur/viabtc-openrpc/blob/main/viabtc-openrpc.json

**Comment by M-Mortaz** [comment]
Thank you for your response, I replaced the content of  https://playground.open-rpc.org/ into `viabtc-openrpc.json` file, but I get the following error.
```
➜  viabtc-openrpc git:(main) ✗ cd docs/gatsby/
➜  gatsby git:(main) ✗ npm run start  

> ViaBTCAPI@1.0.0 start /home/parsezan/work/viabtc-openrpc/docs/gatsby
> npm run develop


> ViaBTCAPI@1.0.0 develop /home/parsezan/work/viabtc-openrpc/docs/gatsby
> gatsby develop

success open and validate gatsby-configs - 0.104s
success load plugins - 3.259s
success onPreInit - 0.045s
success initialize cache - 0.025s
success copy gatsby files - 0.070s
success onPreBootstrap - 0.032s
success createSchemaCustomization - 0.007s
success Checking for changed pages - 0.004s
success source and transform nodes - 0.363s
success building schema - 0.304s
info Total nodes: 52, SitePage nodes: 2 (use --verbose for breakdown)
success createPages - 0.049s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.116s
success update schema - 0.023s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.130s
success onPostBootstrap - 0.136s
info bootstrap finished - 10.616s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.739s
success write out requires - 0.003s
success run static queries - 0.422s - 5/5 11.85/s
success run page queries - 0.025s - 3/3 122.02/s
⠸ Building development bundle
TypeError: (0 , _createSvgIcon.default) is not a function
    at Object../node_modules/@xops.net/gatsby-openrpc-theme/node_modules/@material-ui/icons/Brightness3.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:42052:43)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Module../node_modules/@xops.net/gatsby-openrpc-theme/src/layouts/index.tsx (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:42290:88)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Object../node_modules/gatsby-plugin-layout/wrap-page.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:83482:26)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Object../node_modules/gatsby-plugin-layout/gatsby-ssr.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:83459:27)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Object../.cache/api-runner-ssr.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:163:11)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at Module../.cache/develop-static-entry.js (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:559:73)
    at __webpack_require__ (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:36:30)
    at /home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:127:18
    at /home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:130:10
    at webpackUniversalModuleDefinition (/home/parsezan/work/viabtc-openrpc/docs/gatsby/public/render-page.js:3:20)

 ERROR 

There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html TypeError: (0 , _createSvgIcon.default) is not
a function


  14 | var _createSvgIcon = _interopRequireDefault(require("./utils/createSvgIcon"));
  15 |
> 16 | var _default = (0, _createSvgIcon.default)( /*#__PURE__*/React.createElement("path", {
     |                ^
  17 |   d: "M9 2c-1.05 0-2.05.16-3 .46 4.06 1.27 7 5.06 7 9.54 0 4.48-2.94 8.27-7 9.54.95.3 1.95.46 3 .46 5.52 0 10-4.48 
10-10S14.52 2 9 2z"
  18 | }), 'Brightness3');
  19 |


  WebpackError: TypeError: (0 , _createSvgIcon.default) is not a function
  
  - Brightness3.js:16 
    [gatsby-openrpc-theme]/[@material-ui]/icons/Brightness3.js:16:16
  
  - wrap-page.js:12 
    node_modules/gatsby-plugin-layout/wrap-page.js:12:26
  
  - gatsby-ssr.js:3 
    node_modules/gatsby-plugin-layout/gatsby-ssr.js:3:27
  

not finished Building development bundle - 19.337s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViaBTCAPI@1.0.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ViaBTCAPI@1.0.0 develop script.
```

**Comment by ceyonur** [comment]
no no you should do the exact opposite :) copy from `viabtc-openrpc.json` and paste into https://playground.open-rpc.org/
